version: '3'
services:
  php-console-v2:
    container_name: php-console-v2
    image: php-console:v2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/www:rw
    ports:
      - 9001:9001
    restart: always  
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
 default:
    name: php-console-v2
